#!/usr/bin/env python3
"""Replace button_handler and message_handler with full working versions, fix admin menu & PDF."""

with open("phantomwatch.py", "r") as f:
    lines = f.readlines()

# ========== 1. Replace button_handler completely ==========
start_bh = None
end_bh = None
for i, line in enumerate(lines):
    if line.strip().startswith("async def button_handler("):
        start_bh = i
    if start_bh is not None and i > start_bh and line.strip().startswith("async def message_handler("):
        end_bh = i
        break

if start_bh is None or end_bh is None:
    print("❌ Could not find button_handler or message_handler.")
else:
    new_button_handler = [
        'async def button_handler(update, context):\n',
        '    query = update.callback_query\n',
        '    await query.answer()\n',
        '    data = query.data\n',
        '    username = query.from_user.username\n',
        '\n',
        '    if data == "main_menu":\n',
        '        try:\n',
        '            await query.edit_message_text("⬇️ Main Menu:", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data == "scan_full":\n',
        '        if not is_active(username):\n',
        '            await query.edit_message_text("⛔ Not authorized or trial expired.")\n',
        '            return\n',
        '        context.user_data["scan_type"] = "full"\n',
        '        context.user_data["tools"] = None\n',
        '        try:\n',
        '            await query.edit_message_text("📌 Send the domain name to scan.")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "SCAN_DOMAIN"\n',
        '        return\n',
        '\n',
        '    if data == "scan_quick":\n',
        '        if not is_active(username):\n',
        '            await query.edit_message_text("⛔ Not authorized or trial expired.")\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("Choose a quick scan type:", reply_markup=quick_scan_menu())\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data.startswith("quick_"):\n',
        '        if not is_active(username):\n',
        '            await query.edit_message_text("⛔ Not authorized or trial expired.")\n',
        '            return\n',
        '        if data == "quick_ports":\n',
        '            tools = ["nmap", "nikto"]\n',
        '        elif data == "quick_osint":\n',
        '            tools = ["theHarvester", "sherlock"]\n',
        '        elif data == "quick_recon":\n',
        '            tools = ["whatweb", "dnstwist", "metagoofil"]\n',
        '        elif data == "quick_xss":\n',
        '            tools = ["dalfox"]\n',
        '        context.user_data["tools"] = tools\n',
        '        context.user_data["scan_type"] = "quick"\n',
        '        try:\n',
        '            await query.edit_message_text("📌 Send the domain name to scan.")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "SCAN_DOMAIN"\n',
        '        return\n',
        '\n',
        '    if data == "set_email":\n',
        '        try:\n',
        '            await query.edit_message_text("📧 Please send your email address:")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "SET_EMAIL"\n',
        '        return\n',
        '\n',
        '    if data == "pricing":\n',
        '        pricing_text = (\n',
        '            "💲 *Phantom Watch Pricing Plans*\\n"\n',
        '            "━━━━━━━━━━━━━━━\\n\\n"\n',
        '            "🆓 *Free Trial — 7 Days*\\n"\n',
        '            "   Perfect for testing the platform\\n\\n"\n',
        '            "   ✔ One full security scan\\n"\n',
        '            "   ✔ Basic findings summary\\n"\n',
        '            "   ✔ Exposure & vulnerability overview\\n"\n',
        '            "   ✔ Limited reporting features\\n\\n"\n',
        '            "   💵 *Price:* Free\\n\\n"\n',
        '            "🛡️ *Monthly Plan — $199/month*\\n"\n',
        '            "   Designed for growing businesses\\n\\n"\n',
        '            "   ✔ Unlimited full scans\\n"\n',
        '            "   ✔ Professional PDF reports\\n"\n',
        '            "   ✔ Compliance mapping\\n"\n',
        '            "   ✔ Breach intelligence monitoring\\n"\n',
        '            "   ✔ Weekly automated scans\\n"\n',
        '            "   ✔ Continuous exposure tracking\\n"\n',
        '            "   ✔ Priority vulnerability alerts\\n\\n"\n',
        '            "   💵 *Price:* $199/month\\n\\n"\n',
        '            "👑 *Enterprise Plan — $2,000/month*\\n"\n',
        '            "   Advanced protection for organizations\\n\\n"\n',
        '            "   ✔ Everything in Monthly Plan\\n"\n',
        '            "   ✔ Exploitation proof screenshots\\n"\n',
        '            "   ✔ Continuous CVE monitoring\\n"\n',
        '            "   ✔ GitHub secret scanning\\n"\n',
        '            "   ✔ Advanced OSINT intelligence\\n"\n',
        '            "   ✔ Priority support & escalation\\n"\n',
        '            "   ✔ Dedicated monitoring workflows\\n"\n',
        '            "   ✔ Enhanced reporting & analytics\\n\\n"\n',
        '            "   💵 *Price:* $2,000/month\\n\\n"\n',
        '            "━━━━━━━━━━━━━━━\\n"\n',
        '            "📩 *Need Access or an Upgrade?*\\n"\n',
        '            "Contact the admin to activate your plan."\n',
        '        )\n',
        '        await context.bot.send_message(chat_id=query.message.chat_id, text=pricing_text, parse_mode="Markdown")\n',
        '        try:\n',
        '            await query.edit_message_text("🔮 Return to main menu:", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data == "how_it_works":\n',
        '        how_text = (\n',
        '            "📖 *How Phantom Watch Works*\\n"\n',
        '            "━━━━━━━━━━━━━━━\\n\\n"\n',
        '            "1️ *Registration & Verification*\\n"\n',
        '            "   └ Your organization is added by the admin\\n"\n',
        '            "   └ Domain ownership is verified securely\\n"\n',
        '            "   └ Scanning scope is configured\\n\\n"\n',
        '            "2️ *Choose Your Scan Type*\\n"\n',
        '            "   └ ⚡ *Quick Scan* → Fast exposure checks\\n"\n',
        '            "   └ 🛡 *Full Scan* → Deep vulnerability assessment\\n"\n',
        '            "   └ Targets can include domains, subdomains,\\n"\n',
        '            "      web apps, and public assets\\n\\n"\n',
        '            "3️ *Automated Security Analysis*\\n"\n',
        '            "   └ Port & service discovery\\n"\n',
        '            "   └ Website technology detection\\n"\n',
        '            "   └ Vulnerability identification\\n"\n',
        '            "   └ Breach & leaked credential checks\\n"\n',
        '            "   └ GitHub secret exposure scanning\\n\\n"\n',
        '            "4️ *Live Monitoring & Alerts*\\n"\n',
        '            "   └ Critical findings are reported instantly\\n"\n',
        '            "   └ High-risk exposures are prioritized\\n"\n',
        '            "   └ Continuous tracking for new threats\\n\\n"\n',
        '            "5️ *Professional Reporting*\\n"\n',
        '            "   └ Detailed PDF security reports\\n"\n',
        '            "   └ Compliance mapping included\\n"\n',
        '            "   └ Clear remediation recommendations\\n"\n',
        '            "   └ Executive-friendly summaries\\n\\n"\n',
        '            "6️ *Continuous Protection*\\n"\n',
        '            "   └ Weekly or scheduled scans\\n"\n',
        '            "   └ Ongoing breach monitoring\\n"\n',
        '            "   └ Long-term security visibility\\n\\n"\n',
        '            "━━━━━━━━━━━━━━━\\n"\n',
        '            "💡 *Enterprise Features*\\n"\n',
        '            "Exploitation proof • Advanced OSINT • GitHub secret scanning • Priority monitoring"\n',
        '        )\n',
        '        await context.bot.send_message(chat_id=query.message.chat_id, text=how_text, parse_mode="Markdown")\n',
        '        try:\n',
        '            await query.edit_message_text("🔮 Return to main menu:", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data == "check_breaches":\n',
        '        if not is_active(username):\n',
        '            await query.edit_message_text("⛔ Not authorized or trial expired.")\n',
        '            return\n',
        '        c.execute("SELECT email_collect FROM clients WHERE username=?", (username,))\n',
        '        row = c.fetchone()\n',
        '        email = row[0] if row else ""\n',
        '        if not email:\n',
        '            await query.edit_message_text("📧 Please set your email first using the *Set Email* button.")\n',
        '        else:\n',
        '            await query.edit_message_text("🩸 Checking breaches...")\n',
        '            await check_breach(email, context, query.message.chat_id)\n',
        '        return\n',
        '\n',
        '    if data == "subscribe":\n',
        '        if not is_active(username):\n',
        '            await query.edit_message_text("⛔ Not authorized or trial expired.")\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("📌 Send the domain you want to monitor weekly:")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "SUBSCRIBE_DOMAIN"\n',
        '        return\n',
        '\n',
        '    if data == "github_scan":\n',
        '        if not is_client(username):\n',
        '            await query.edit_message_text("🔑 This feature requires Enterprise plan.")\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("🔑 Send the GitHub repository URL (e.g., https://github.com/user/repo):")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "GITHUB_SCAN"\n',
        '        return\n',
        '\n',
        '    if data == "help":\n',
        '        help_text = (\n',
        '            "🛠 *Security Toolkit*\\n"\n',
        '            "━━━━━━━━━━━━━━━\\n\\n"\n',
        '            "⚡ *Nmap*\\n   └ Ports & vulnerability discovery\\n\\n"\n',
        '            "🕵️ *Nikto*\\n   └ Web server vulnerability scanning\\n\\n"\n',
        '            "🔎 *WhatWeb*\\n   └ Website technology fingerprinting\\n\\n"\n',
        '            "📧 *theHarvester*\\n   └ Email & OSINT collection\\n\\n"\n',
        '            "🔄 *dnstwist*\\n   └ Detect fake / typosquatted domains\\n\\n"\n',
        '            "📄 *Metagoofil*\\n   └ Extract metadata from public files\\n\\n"\n',
        '            "👤 *Sherlock*\\n   └ Social media username tracking\\n\\n"\n',
        '            "🦠 *Dalfox*\\n   └ Automated XSS scanning\\n\\n"\n',
        '            "🩸 *Check Breaches*\\n   └ Email breach lookup\\n\\n"\n',
        '            "🔑 *GitHub Scan*\\n   └ Detect exposed secrets & keys\\n\\n"\n',
        '            "━━━━━━━━━━━━━━━\\n"\n',
        '            "🚀 *Upgrade Available*\\n"\n',
        '            "PDF reports • Compliance mapping • Advanced scans"\n',
        '        )\n',
        '        await context.bot.send_message(chat_id=query.message.chat_id, text=help_text, parse_mode="Markdown")\n',
        '        try:\n',
        '            await query.edit_message_text("🔮 Return to main menu:", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data == "contact_admin":\n',
        '        msg = f"📩 Contact the admin directly: @{ADMIN_USERNAME}\\n\\n👉 https://t.me/{ADMIN_USERNAME}"\n',
        '        try:\n',
        '            await query.edit_message_text(msg)\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    # Admin\n',
        '    if data == "admin_menu":\n',
        '        if username != ADMIN_USERNAME:\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("👑 Admin Panel:", reply_markup=admin_menu())\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data == "admin_adduser":\n',
        '        if username != ADMIN_USERNAME:\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("Enter client username (with @):")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "ADDUSER_USERNAME"\n',
        '        return\n',
        '\n',
        '    if data == "admin_verify":\n',
        '        if username != ADMIN_USERNAME:\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("Enter client username (with @):")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "VERIFY_USERNAME"\n',
        '        return\n',
        '\n',
        '    if data == "admin_status":\n',
        '        if username != ADMIN_USERNAME:\n',
        '            return\n',
        '        c.execute("SELECT username, plan, expiry FROM clients")\n',
        '        clients = c.fetchall()\n',
        '        msg = "📊 Client List\\n\\n"\n',
        '        for u, p, e in clients:\n',
        '            msg += f"@{u} - {p}"\n',
        '            if e: msg += f" (exp: {e})"\n',
        '            msg += "\\n"\n',
        '        try:\n',
        '            await query.edit_message_text(msg, reply_markup=admin_menu())\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        return\n',
        '\n',
        '    if data == "admin_removeuser":\n',
        '        if username != ADMIN_USERNAME:\n',
        '            return\n',
        '        try:\n',
        '            await query.edit_message_text("Enter the username of the client to remove (with @):")\n',
        '        except Exception as e:\n',
        '            if "Message is not modified" not in str(e):\n',
        '                print(f"Edit error: {e}")\n',
        '        context.user_data["state"] = "REMOVE_USER"\n',
        '        return\n',
        '\n',
    ]

    # ========== 2. Replace message_handler completely ==========
    start_mh = None
    end_mh = None
    for i, line in enumerate(lines):
        if line.strip().startswith("async def message_handler("):
            start_mh = i
        if start_mh is not None and i > start_mh and (line.strip().startswith("def main()") or line.strip().startswith("# ---------- Main")):
            end_mh = i
            break

    if start_mh is None or end_mh is None:
        print("❌ Could not find message_handler or main.")
    else:
        new_message_handler = [
            'async def message_handler(update, context):\n',
            '    username = update.message.from_user.username\n',
            '    text = update.message.text.strip()\n',
            '    state = context.user_data.get("state")\n',
            '\n',
            '    # Persistent menu button\n',
            '    if text == "🛡️ Menu":\n',
            '        await update.message.reply_text("Menu:", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
            '        return\n',
            '\n',
            '    if state == "SET_EMAIL":\n',
            '        if "@" not in text:\n',
            '            await update.message.reply_text("Invalid email.")\n',
            '            return\n',
            '        c.execute("UPDATE clients SET email_collect=? WHERE username=?", (text, username))\n',
            '        conn.commit()\n',
            '        await update.message.reply_text(f"✅ Email set.", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
            '        context.user_data.pop("state", None)\n',
            '        return\n',
            '\n',
            '    if state == "SUBSCRIBE_DOMAIN":\n',
            '        domain = text.lower()\n',
            '        if not re.match(r"^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$", domain):\n',
            '            await update.message.reply_text("Invalid domain.")\n',
            '            return\n',
            '        c.execute("INSERT OR REPLACE INTO subscriptions VALUES (?,?,?,?)", (username, domain, datetime.now().isoformat(), "{}"))\n',
            '        conn.commit()\n',
            '        await update.message.reply_text(f"✅ Subscribed to weekly scans for {domain}.", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
            '        context.user_data.pop("state", None)\n',
            '        return\n',
            '\n',
            '    if state == "GITHUB_SCAN":\n',
            '        repo_url = text.strip()\n',
            '        if not repo_url.startswith("https://github.com/"):\n',
            '            await update.message.reply_text("Invalid GitHub URL.")\n',
            '            return\n',
            '        await update.message.reply_text("🔑 Scanning for secrets...")\n',
            '        try:\n',
            '            repo_name = repo_url.rstrip("/").split("/")[-1]\n',
            '            clone_dir = f"/tmp/{repo_name}_{random.randint(1000,9999)}"\n',
            '            subprocess.run(["git", "clone", "--depth=1", repo_url, clone_dir], check=True, timeout=30)\n',
            '            result = subprocess.run(["trufflehog", "filesystem", clone_dir, "--no-update", "--json"],\n',
            '                                    capture_output=True, text=True, timeout=120)\n',
            '            shutil.rmtree(clone_dir, ignore_errors=True)\n',
            '            findings = [json.loads(line) for line in result.stdout.splitlines() if line.strip()]\n',
            '            if not findings:\n',
            '                await update.message.reply_text("✅ No secrets detected.")\n',
            '            else:\n',
            '                summary = f"🔑 *Found {len(findings)} secrets!*\\n"\n',
            '                for f in findings[:5]:\n',
            '                    summary += f"• {f.get(\'DetectorName\',\'Unknown\')} in {f.get(\'SourceMetadata\',{}).get(\'Data\',{}).get(\'Filesystem\',{}).get(\'file\',\'unknown\')}\\n"\n',
            '                await update.message.reply_text(summary, parse_mode="Markdown")\n',
            '        except Exception as e:\n',
            '            await update.message.reply_text(f"❌ GitHub scan failed: {e}")\n',
            '        context.user_data.pop("state", None)\n',
            '        return\n',
            '\n',
            '    if state == "REMOVE_USER":\n',
            '        if username != ADMIN_USERNAME:\n',
            '            await update.message.reply_text("❌ Admin only.")\n',
            '            return\n',
            '        target = text.lstrip("@")\n',
            '        if not is_client(target):\n',
            '            await update.message.reply_text("User is not a client.")\n',
            '            return\n',
            '        c.execute("UPDATE clients SET expiry=\'2000-01-01\' WHERE username=?", (target,))\n',
            '        conn.commit()\n',
            '        await update.message.reply_text(f"❌ User @{target} has been removed. They can no longer use the bot.", reply_markup=admin_menu())\n',
            '        context.user_data.pop("state", None)\n',
            '        return\n',
            '\n',
            '    if state == "ADDUSER_USERNAME":\n',
            '        if username != ADMIN_USERNAME:\n',
            '            await update.message.reply_text("❌ Admin only.")\n',
            '            return\n',
            '        target = text.lstrip("@")\n',
            '        if not target:\n',
            '            await update.message.reply_text("Invalid username.")\n',
            '            return\n',
            '        context.user_data["add_target"] = target\n',
            '        await update.message.reply_text("Plan? (free, monthly, enterprise):")\n',
            '        context.user_data["state"] = "ADDUSER_PLAN"\n',
            '        return\n',
            '\n',
            '    if state == "ADDUSER_PLAN":\n',
            '        plan = text.lower()\n',
            '        if plan not in ["free", "monthly", "enterprise"]:\n',
            '            await update.message.reply_text("Invalid plan. Use free, monthly, or enterprise:")\n',
            '            return\n',
            '        context.user_data["add_plan"] = plan\n',
            '        await update.message.reply_text("How many months? (0 for free trial):")\n',
            '        context.user_data["state"] = "ADDUSER_MONTHS"\n',
            '        return\n',
            '\n',
            '    if state == "ADDUSER_MONTHS":\n',
            '        try:\n',
            '            months = int(text)\n',
            '        except:\n',
            '            await update.message.reply_text("Enter a number.")\n',
            '            return\n',
            '        target = context.user_data["add_target"]\n',
            '        plan = context.user_data["add_plan"]\n',
            '        add_client(target, plan, months)\n',
            '        await update.message.reply_text(f"✅ Added @{target} with {plan} plan.", reply_markup=admin_menu())\n',
            '        for k in ("add_target", "add_plan", "state"):\n',
            '            context.user_data.pop(k, None)\n',
            '        return\n',
            '\n',
            '    # ----- ADMIN VERIFY DOMAIN -----\n',
            '    if state == "VERIFY_USERNAME":\n',
            '        if username != ADMIN_USERNAME:\n',
            '            await update.message.reply_text("❌ Admin only.")\n',
            '            return\n',
            '        target = text.lstrip("@")\n',
            '        if not is_client(target):\n',
            '            await update.message.reply_text("User not a client.")\n',
            '            return\n',
            '        context.user_data["verify_target"] = target\n',
            '        await update.message.reply_text("Domain to verify (e.g., example.com):")\n',
            '        context.user_data["state"] = "VERIFY_DOMAIN"\n',
            '        return\n',
            '\n',
            '    if state == "VERIFY_DOMAIN":\n',
            '        target = context.user_data["verify_target"]\n',
            '        domain = text.lower()\n',
            '        c.execute("INSERT OR REPLACE INTO verification VALUES (?,?,?)", (target, domain, "admin_verified"))\n',
            '        conn.commit()\n',
            '        await update.message.reply_text(f"✅ Domain {domain} verified for @{target}.", reply_markup=admin_menu())\n',
            '        context.user_data.pop("state", None)\n',
            '        context.user_data.pop("verify_target", None)\n',
            '        return\n',
            '\n',
            '    if state == "SCAN_DOMAIN":\n',
            '        domain = text.lower()\n',
            '        if not re.match(r"^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$", domain):\n',
            '            await update.message.reply_text("❌ Invalid domain.")\n',
            '            return\n',
            '        if not is_active(username):\n',
            '            await update.message.reply_text("⛔ Not authorized or trial expired.")\n',
            '            return\n',
            '\n',
            '        if username != ADMIN_USERNAME:\n',
            '            c.execute("SELECT token FROM verification WHERE username=? AND domain=?", (username, domain))\n',
            '            row = c.fetchone()\n',
            '            if row and row[0] == "admin_verified":\n',
            '                pass\n',
            '            elif row and row[0] != "admin_verified":\n',
            '                if not verify_domain(domain, row[0]):\n',
            '                    await update.message.reply_text("⏳ Verification file missing.")\n',
            '                    return\n',
            '            else:\n',
            '                token = generate_token()\n',
            '                c.execute("INSERT OR REPLACE INTO verification VALUES (?,?,?)", (username, domain, token))\n',
            '                conn.commit()\n',
            '                await update.message.reply_text(\n',
            '                    f"🔐 To verify, upload a file `verify.txt` with token:\\n`{token}`\\nto the root of your site, then send the domain again."\n',
            '                )\n',
            '                return\n',
            '\n',
            '        await update.message.reply_text("✅ Domain verified. Launching scan...")\n',
            '        chat_id = update.message.chat_id\n',
            '\n',
            '        progress_msg = await context.bot.send_message(chat_id=chat_id, text="⚡ Preparing tools...")\n',
            '        loop = asyncio.get_running_loop()\n',
            '\n',
            '        def sync_progress(msg):\n',
            '            async def _upd():\n',
            '                try:\n',
            '                    await progress_msg.edit_text(msg)\n',
            '                except:\n',
            '                    pass\n',
            '            asyncio.run_coroutine_threadsafe(_upd(), loop)\n',
            '\n',
            '        c.execute("SELECT email_collect FROM clients WHERE username=?", (username,))\n',
            '        row = c.fetchone()\n',
            '        email = row[0] if row else ""\n',
            '        tools = context.user_data.get("tools", None)\n',
            '\n',
            '        results = await loop.run_in_executor(None, run_scan, domain, email, sync_progress, tools)\n',
            '\n',
            '        try:\n',
            '            await progress_msg.delete()\n',
            '        except:\n',
            '            pass\n',
            '\n',
            '        if results:\n',
            '            summary = format_summary(domain, results)\n',
            '            await context.bot.send_message(chat_id=chat_id, text=summary, parse_mode="Markdown")\n',
            '\n',
            '            # Mark free plan as used\n',
            '            c.execute("SELECT plan FROM clients WHERE username=?", (username,))\n',
            '            row = c.fetchone()\n',
            '            plan = row[0] if row else "free"\n',
            '            if plan == "free":\n',
            '                c.execute("UPDATE clients SET scan_used=1 WHERE username=?", (username,))\n',
            '                conn.commit()\n',
            '\n',
            '            # PDF for monthly/enterprise\n',
            '            c.execute("SELECT plan FROM clients WHERE username=?", (username,))\n',
            '            row = c.fetchone()\n',
            '            plan = row[0] if row else "free"\n',
            '            if plan in ("monthly", "enterprise"):\n',
            '                try:\n',
            '                    pdf_buf = generate_pdf_report(domain, results, plan)\n',
            '                    pdf_buf.name = f"PhantomWatch-{domain}-report.pdf"\n',
            '                    await context.bot.send_document(chat_id=chat_id, document=pdf_buf, caption="📎 Detailed compliance report")\n',
            '                except Exception as e:\n',
            '                    await context.bot.send_message(chat_id=chat_id, text=f"⚠️ PDF generation failed: {e}")\n',
            '        else:\n',
            '            await context.bot.send_message(chat_id=chat_id, text="❌ Scan failed.")\n',
            '\n',
            '        context.user_data.pop("state", None)\n',
            '        context.user_data.pop("scan_type", None)\n',
            '        context.user_data.pop("tools", None)\n',
            '        await update.message.reply_text("🔮 What\'s next?", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
            '        return\n',
            '\n',
            '    # Fallback\n',
            '    await update.message.reply_text("I didn\'t understand. Use the buttons below.", reply_markup=main_menu(username == ADMIN_USERNAME))\n',
            '\n',
        ]

    # ========== 3. Apply replacements ==========
    new_lines = lines[:start_bh] + new_button_handler + lines[end_bh:start_mh] + new_message_handler + lines[end_mh:]

    # ========== 4. Fix PDF ln=True if broken ==========
    content = ''.join(new_lines)
    content = content.replace('new_x="LMARGIN", new_y="NEXT"', "ln=True")

    # ========== 5. Ensure admin_menu has Status button ==========
    old_admin_menu = '''def admin_menu():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("➕ Add User", callback_data="admin_adduser"),
         InlineKeyboardButton("✅ Verify Domain", callback_data="admin_verify")],
        [InlineKeyboardButton("❌ Remove User", callback_data="admin_removeuser"),
         InlineKeyboardButton("🔙 Main Menu", callback_data="main_menu")],
    ])'''
    new_admin_menu = '''def admin_menu():
    return InlineKeyboardMarkup([
        [InlineKeyboardButton("➕ Add User", callback_data="admin_adduser"),
         InlineKeyboardButton("✅ Verify Domain", callback_data="admin_verify")],
        [InlineKeyboardButton("📊 Status", callback_data="admin_status")],
        [InlineKeyboardButton("❌ Remove User", callback_data="admin_removeuser"),
         InlineKeyboardButton("🔙 Main Menu", callback_data="main_menu")],
    ])'''
    if old_admin_menu in content:
        content = content.replace(old_admin_menu, new_admin_menu)

    with open("phantomwatch.py", "w") as f:
        f.write(content)

    print("✅ button_handler and message_handler replaced with full admin controls. Status button restored.")
