#!/usr/bin/env python3
"""Replace lines 107-136 with the new full-tool format_summary."""

with open("phantomwatch.py", "r") as f:
    lines = f.readlines()

# New function (each line must end with \n)
new_func = [
    'def format_summary(domain, results):\n',
    '    lines = [f"🔍 Scan completed for {domain}\\n"]\n',
    '    # Nmap\n',
    '    if \'nmap\' in results:\n',
    '        ports = len(re.findall(r"^\\d+/tcp\\s+open\\s+", results.get(\'nmap\',\'\'), re.MULTILINE))\n',
    '        vulns = len(re.findall(r"\\|.*VULNERABLE.*", results.get(\'nmap\',\'\')))\n',
    '        if ports or vulns:\n',
    '            lines.append(f"🛡️ Nmap: {ports} open ports, {vulns} potential vulns")\n',
    '        else:\n',
    '            lines.append("🛡️ Nmap: No open ports or vulns found.")\n',
    '    else:\n',
    '        lines.append("🛡️ Nmap: Not run.")\n',
    '    # Nikto\n',
    '    if \'nikto\' in results:\n',
    '        issues = len(re.findall(r"\\+ (.*)", results.get(\'nikto\',\'\')))\n',
    '        if issues:\n',
    '            lines.append(f"🔥 Nikto: {issues} web issues")\n',
    '        else:\n',
    '            lines.append("🔥 Nikto: No web issues found.")\n',
    '    else:\n',
    '        lines.append("🔥 Nikto: Not run.")\n',
    '    # WhatWeb\n',
    '    if \'whatweb\' in results:\n',
    '        clean = re.sub(r\'\\x1b\\[[0-9;]*m\', \'\', results.get(\'whatweb\',\'\'))\n',
    '        servers = re.findall(r\'HTTPServer\\[ (.*?) \\]\', clean)\n',
    '        if servers:\n',
    '            lines.append(f"🧩 Technology: {servers[0]}")\n',
    '        else:\n',
    '            lines.append("🧩 Technology: No server header detected.")\n',
    '    else:\n',
    '        lines.append("🧩 Technology: Not run.")\n',
    '    # theHarvester\n',
    '    if \'theHarvester\' in results:\n',
    '        harvest = results[\'theHarvester\']\n',
    '        if harvest == "No email":\n',
    '            lines.append("📧 theHarvester: No email set – skipped.")\n',
    '        elif "<html" in harvest.lower():\n',
    '            emails = re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}", harvest)\n',
    '            if emails:\n',
    '                lines.append(f"📧 Emails leaked: {len(emails)}")\n',
    '            else:\n',
    '                lines.append("📧 theHarvester: No leaked emails found.")\n',
    '        else:\n',
    '            lines.append("📧 theHarvester: No results.")\n',
    '    else:\n',
    '        lines.append("📧 theHarvester: Not run.")\n',
    '    # dnstwist\n',
    '    if \'dnstwist\' in results:\n',
    '        registered = len(re.findall(r"^([^ ]+)\\s+registered.*", results.get(\'dnstwist\',\'\'), re.MULTILINE))\n',
    '        if registered:\n',
    '            lines.append(f"🕵️ Typosquatting: {registered} domains registered")\n',
    '        else:\n',
    '            lines.append("🕵️ Typosquatting: No similar domains registered.")\n',
    '    else:\n',
    '        lines.append("🕵️ dnstwist: Not run.")\n',
    '    # Metagoofil\n',
    '    if \'metagoofil\' in results:\n',
    '        if "No metadata" in results.get(\'metagoofil\',\'\'):\n',
    '            lines.append("📄 Metagoofil: No metadata leaks found.")\n',
    '        else:\n',
    '            lines.append("📄 Document metadata leaks found")\n',
    '    else:\n',
    '        lines.append("📄 Metagoofil: Not run.")\n',
    '    # Sherlock\n',
    '    if \'sherlock\' in results:\n',
    '        found = len(re.findall(r"\\[\\+\\] (.*)", results.get(\'sherlock\',\'\')))\n',
    '        if found:\n',
    '            lines.append(f"👥 Social media: {found} accounts found")\n',
    '        else:\n',
    '            lines.append("👥 Social media: No accounts found.")\n',
    '    else:\n',
    '        lines.append("👥 Sherlock: Not run.")\n',
    '    lines.append("\\n⚠️ Upgrade to Monthly/Enterprise for full PDF reports & compliance mapping.")\n',
    '    return "\\n".join(lines)\n',
]

# Replace lines 107-136 (Python indexes 106-135)
new_lines = lines[:106] + new_func + lines[136:]
with open("phantomwatch.py", "w") as f:
    f.writelines(new_lines)

print("✅ format_summary replaced with full-tool version.")
